workflows:
  android-debug:
    name: Build Android Debug APK
    max_build_duration: 60
    environment:
      java: 17
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build Debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
